# Numpy

In [1]:
import numpy as np

In [2]:
a = np.array(([1,2],[3,4]))

In [3]:
a

array([[1, 2],
       [3, 4]])

## basic indexing

In [7]:
x = np.arange(5,10)

In [8]:
x

array([5, 6, 7, 8, 9])

In [12]:
x[-2]

8

## basic slicing and striding

In [13]:
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])    # np.arange(10)

In [17]:
x[1:7:3]   #i,j,k :  i is the starting index, j is the stopping index, and k is the step 

array([1, 4])

In [15]:
x[1:7]

array([1, 2, 3, 4, 5, 6])

In [18]:
x[:4]

array([0, 1, 2, 3])

In [19]:
x[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
x[-1]

9

In [21]:
x[:-3]

array([0, 1, 2, 3, 4, 5, 6])

In [22]:
x[-3:]

array([7, 8, 9])

## advanced indexing

Integer array indexing

In [26]:
x = np.arange(5,15)
x

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [28]:
x[np.array([4,2])]

array([9, 7])

## repeat

In [36]:
a = np.array(([1,2],[3,4]))
a.shape

(2, 2)

In [33]:
np.repeat(a, 3,axis=1)

array([[1, 1, 1, 2, 2, 2],
       [3, 3, 3, 4, 4, 4]])

In [34]:
np.repeat(a, 2,axis=1)

array([[1, 1, 2, 2],
       [3, 3, 4, 4]])

In [35]:
np.repeat(a, 2,axis=-1)

array([[1, 1, 2, 2],
       [3, 3, 4, 4]])

## flatten

In [37]:
a.flatten()

array([1, 2, 3, 4])

In [38]:
b = np.array(([5,6],[7,8]))

In [ ]:
b

## concatenate

In [39]:
np.concatenate((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [40]:
np.concatenate((a,b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [41]:
np.concatenate((a,b), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

## transpose

In [42]:
np.transpose(a)

array([[1, 3],
       [2, 4]])

## reshape

In [43]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [52]:
np.arange(12).reshape((2,-1,3))

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [49]:
a = np.array([[1,2,3], [4,5,6]])
np.reshape(a,6)

array([1, 2, 3, 4, 5, 6])

In [50]:
np.reshape(a, (3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [51]:
np.reshape(a, (3,-1,))

array([[1, 2],
       [3, 4],
       [5, 6]])

## squeeze

remove axes of length one from input

In [53]:
t = np.arange(6)

In [54]:
t.shape

(6,)

In [56]:
t = np.reshape(t,(6,1))

In [57]:
t.shape

(6, 1)

In [58]:
np.squeeze(t)

array([0, 1, 2, 3, 4, 5])

## stack

Join a sequence of arrays along a new axis.

In [ ]:
array = np.random.randn(3, 4) 
array

In [ ]:
arrays = [np.random.randn(3, 4) for _ in range(10)]
arrays

In [ ]:
arrays

In [ ]:
np.stack(arrays, axis=0).shape

In [ ]:
np.stack(arrays, axis=1).shape

In [ ]:
np.stack(arrays, axis=2).shape

## vstack

stack arrays in sequence vertically (row wise)

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [ ]:
np.vstack((a,b))

In [ ]:
a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])

In [ ]:
np.vstack((a,b))

## hstack

Stack arrays in sequence horizontally (column wise)

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [ ]:
np.hstack((a,b))

In [ ]:
a = np.array([[1],[2],[3]])
b = np.array([[4],[5],[6]])

In [ ]:
np.hstack((a,b))

## split

Split an array into multiple sub-arrays as views into ary.

In [ ]:
x = np.arange(9.0)

In [ ]:
np.split(x, 3)

In [ ]:
np.split(x, 4)

In [ ]:
x = np.arange(8.0)
np.split(x, [3, 5, 6, 10])

## flip

Reverse the order of elements in an array along the given axis.

The shape of the array is preserved, but the elements are reordered.

In [ ]:
A = np.arange(8).reshape((2,2,2))

In [ ]:
A

In [ ]:
np.flip(A,0)

In [ ]:
np.flip(A,1)

In [ ]:
np.flip(A,2)

## trim_zeros

Trim the leading and/or trailing zeros from a 1-D array or sequence.

In [ ]:
a = np.array((0, 0, 0, 1, 2, 3, 0, 2, 1, 0))

In [ ]:
np.trim_zeros(a)

In [ ]:
np.trim_zeros(a,'f')

In [ ]:
np.trim_zeros(a,'b')

In [ ]:
np.ma.masked_equal(a,0)